name: Update OCI Artifacts
on:
  workflow_dispatch:

jobs:
  publish-oci-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Plugins
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19'

      - name: Build registry artifact tool
        working-directory: build/registry
        run: make

      - name: Get lowercase registry user
        run: |
          REPO_OWNER="${{ github.repository_owner }}"
          echo "REGISTRY_USER=${REPO_OWNER,,}" >>${GITHUB_ENV}

      - name: Upload OCI artifacts to GitHub packages
        env:
          REGISTRY: ghcr.io
          REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_GITHUB: https://github.com/${{ github.repository_owner }}/plugins.git
        working-directory: build/registry
        run: ./bin/registry update-oci-registry ../../registry.yaml
